<?php

declare(strict_types=1);

namespace App\Service;

/**
 * I testi che gli operai leggono, nella loro lingua.
 *
 * Solo quello che arriva sul telefono di un operaio: notifiche e poco altro.
 * BOB resta in italiano — chi lo usa sta in ufficio e l'italiano lo parla —
 * e tradurre tutto il gestionale per cinque lingue sarebbe un lavoro
 * enorme che non serve a nessuno.
 *
 * Un array e non un file di traduzioni per lingua: sono una decina di frasi,
 * e tenerle una sotto l'altra fa vedere a colpo d'occhio se ne manca una.
 * Quando saranno cinquanta varra' la pena spostarle.
 *
 * Il moldavo e il rumeno sono la stessa lingua con due nomi: i testi sono
 * identici e "mo" ricade su "ro". Restano due voci distinte perche' e' cosi'
 * che le persone si riconoscono, e obbligare un moldavo a scegliere "rumeno"
 * e' un modo gratuito di dargli fastidio.
 */
final class Lingua
{
    public const DISPONIBILI = [
        'it' => 'Italiano',
        'en' => 'English',
        'sq' => 'Shqip',
        'ro' => 'Romana',
        'mo' => 'Moldoveneasca',
    ];

    private const RIPIEGO = 'it';

    /**
     * @var array<string, array<string, string|string[]>>
     */
    private const TESTI = [
        'it' => [
            'giorni_settimana'     => ['lunedi', 'martedi', 'mercoledi', 'giovedi', 'venerdi', 'sabato', 'domenica'],
            'oggi'                 => 'oggi',
            'e_cong'               => 'e',
            'promemoria_titolo'    => 'Presenza da segnare',
            'promemoria_uno'       => 'Ti manca la presenza di {giorni}. Bastano pochi secondi.',
            'promemoria_piu'       => 'Ti mancano le presenze di {giorni}. Bastano pochi secondi.',
            'promemoria_uno_2'     => 'Ultimo promemoria: ti manca ancora la presenza di {giorni}.',
            'promemoria_piu_2'     => 'Ultimo promemoria: ti mancano ancora le presenze di {giorni}.',
            'esito_presenza_ok'    => 'Presenza approvata',
            'esito_presenza_ko'    => 'Presenza rifiutata',
            'presenza_approvata'   => 'La presenza del {data} e\' stata approvata.',
            'presenza_rifiutata'   => 'La presenza del {data} e\' stata rifiutata: {motivo}',
            'esito_richiesta_ok'   => 'Richiesta approvata',
            'esito_richiesta_ko'   => 'Richiesta rifiutata',
            'cosa_ferie'           => 'ferie',
            'cosa_permesso'        => 'permesso',
            'cosa_malattia'        => 'malattia',

            // ── Le pagine di /io ──────────────────────────
            'lingua_lbl'               => 'Lingua',
            'lingua_aiuto'             => 'Le tue pagine e le notifiche arrivano in questa lingua.',
            'password_da_cambiare'     => 'Prima di cominciare devi scegliere una password tua.',
            'menu_oggi'                => 'Oggi e domani',
            'menu_presenze'            => 'Le mie presenze',
            'menu_assenze'             => 'Ferie e assenze',
            'documenti'                => 'Documenti',
            'menu_cantieri'            => 'I miei cantieri',
            'apri'                     => 'Apri',
            'nessun_cantiere'          => 'Nessun cantiere assegnato.',
            'nome'                     => 'Nome',
            'codice'                   => 'Codice',
            'luogo'                    => 'Luogo',
            'ciao'                     => 'Ciao {nome}',
            'oggi_lbl'                 => 'Oggi',
            'domani_lbl'               => 'Domani',
            'cantiere_da_definire'     => 'Cantiere da definire',
            'auto'                     => 'Auto',
            'trasferta'                => 'Trasferta',
            'dorme_fuori'              => 'Si dorme fuori',
            'squadra'                  => 'Squadra',
            'sei_capo'                 => 'Sei tu il capo',
            'con_te'                   => 'Con te ci sono',
            'tu'                       => 'Tu',
            'capo'                     => 'capo',
            'nessuna_squadra'          => 'Per oggi e domani non risulti in nessuna squadra. Se non torna, chiedi in ufficio.',
            'cosa_puoi_fare'           => 'Cosa puoi fare',
            'ti_manca_una'             => 'Ti manca {n} giornata:',
            'ti_mancano'               => 'Ti mancano {n} giornate:',
            'segnale'                  => 'Segnale',
            'ultimi_due_mesi'          => 'Ultimi due mesi',
            'da_segnare'               => 'Da segnare',
            'giornata_intera'          => 'Giornata intera',
            'mezza_giornata'           => 'Mezza giornata',
            'cantiere_da_scegliere'    => 'Cantiere da scegliere',
            'scegli'                   => 'Scegli',
            'nota_mezza'               => 'Mezza giornata, o hai mangiato fuori? Usa Segna un altro giorno qui sotto.',
            'segna_giornata'           => 'Segna una giornata',
            'segna_altro'              => 'Segna un altro giorno',
            'che_giorno'               => 'Che giorno',
            'dove_lavorato'            => 'Dove hai lavorato',
            'eri_qui'                  => 'Quel giorno eri qui',
            'non_era_questo'           => 'Non era questo cantiere',
            'cerca_cantiere'           => 'Scrivi il nome o il codice',
            'due_lettere'              => 'Scrivi almeno due lettere e aspetta un attimo',
            'quanto_lavorato'          => 'Quanto hai lavorato',
            'extra'                    => 'Pasti, albergo, auto',
            'pranzo_chi'               => 'Pranzo - chi ha pagato?',
            'cena_chi'                 => 'Cena - chi ha pagato?',
            'non_fatto'                => 'Non l\'ho fatto',
            'io'                       => 'Io',
            'azienda'                  => 'L\'azienda',
            'dormito_fuori'            => 'Ho dormito fuori',
            'albergo'                  => 'Albergo',
            'albergo_ph'               => 'Nome, se hai dormito fuori',
            'targa'                    => 'Targa',
            'note'                     => 'Note',
            'note_ph'                  => 'Se c\'e\' qualcosa da dire all\'ufficio',
            'manda'                    => 'Manda in ufficio',
            'controlla_ufficio'        => 'La controlla l\'ufficio prima di registrarla.',
            'tue_giornate'             => 'Le tue giornate',
            'giornate'                 => 'Giornate',
            'in_attesa_n'              => 'In attesa',
            'trasferte'                => 'Trasferte',
            'rifiutate'                => 'Rifiutate',
            'cerca_giornata'           => 'Cerca cantiere o giorno',
            'registrata'               => 'registrata',
            'in_attesa'                => 'in attesa',
            'rifiutata'                => 'rifiutata',
            'approvata'                => 'approvata',
            'non_accettata'            => 'non accettata',
            'rifiutata_due'            => 'Rifiutata:',
            'ritira'                   => 'Ritira',
            'ritirare_conferma'        => 'Ritirare questa giornata?',
            'nessuna_giornata'         => 'Nessuna giornata in questo mese.',
            'nessuna_trovata'          => 'Nessuna giornata trovata.',
            'torna'                    => 'Torna indietro',
            'mese'                     => 'Mese',
            'anno'                     => 'Anno',
            'vai'                      => 'Vai',
            'tue_assenze'              => 'Le tue assenze',
            'chiesto_e_dato'           => 'Quello che hai chiesto e quello che ti hanno dato',
            'chiedi_ferie'             => 'Chiedi ferie o avvisa',
            'di_cosa'                  => 'Di cosa si tratta',
            'ferie'                    => 'Ferie',
            'permesso'                 => 'Permesso',
            'malattia'                 => 'Malattia',
            'dal'                      => 'Dal',
            'al'                       => 'Al',
            'vuoto_un_giorno'          => 'Lascia vuoto se e\' un giorno solo',
            'quante_ore'               => 'Quante ore',
            'vuoto_intera'             => 'Vuoto = giornata intera',
            'n_certificato'            => 'Numero del certificato',
            'cert_dopo'                => 'Se non ce l\'hai adesso, lo aggiunge l\'ufficio',
            'note_qualcosa'            => 'Se c\'e\' qualcosa da dire',
            'giorni_ferie'             => 'Giorni ferie',
            'permessi'                 => 'Permessi',
            'giorni_malattia'          => 'Giorni malattia',
            'cerca_assenza'            => 'Cerca tipo, data o stato',
            'nessuna_assenza'          => 'Nessuna ferie, permesso o malattia in questo anno.',
            'nessuna_assenza_trovata'  => 'Nessuna assenza trovata.',
            'ore'                      => 'ore',
            'cert'                     => 'cert.',
            'mezza_g'                  => 'mezza giornata',
            'cantiere_non_indicato'    => 'cantiere non indicato',

            // ── Cosa gli si dice dopo che ha fatto qualcosa ──
            'msg_scegli_tutto'         => 'Scegli il cantiere e il giorno.',
            'msg_giorno_futuro'        => 'Non puoi segnare un giorno che deve ancora arrivare.',
            'msg_cantiere_chiuso'      => 'Quel cantiere non e\' aperto. Se sbaglio, dillo in ufficio.',
            'msg_gia_mandata'          => 'Hai gia\' mandato questa giornata: e\' in attesa.',
            'msg_mandata'              => 'Giornata del {data} mandata in ufficio. La trovi qui sotto come in attesa.',
            'msg_ritirata'             => 'Giornata ritirata. Puoi rimandarla quando vuoi.',
            'msg_non_ritirabile'       => 'Non si puo\' piu\' ritirare: l\'ufficio l\'ha gia\' guardata.',
            'msg_scegli_tipo'          => 'Scegli il tipo e il giorno di inizio.',
            'msg_richiesta_mandata'    => '{cosa} {quando}: richiesta mandata in ufficio.',
            'msg_non_collegato'        => 'Il tuo utente non e\' collegato a nessun operaio. Dillo in ufficio.',
            'msg_errore'               => 'Qualcosa non ha funzionato: {errore}',
            'per_il'                   => 'del {data}',
            'da_a'                     => 'dal {dal} al {al}',
            'esito_malattia_ok'    => 'Malattia registrata',
            'esito_malattia_ko'    => 'Malattia non accettata',
            'malattia_registrata'  => 'La malattia {periodo} e\' stata registrata.',
            'malattia_rifiutata'   => 'La malattia {periodo} non e\' stata accettata: {motivo}',
            'periodo_giorno'       => 'del {dal}',
            'periodo_dal_al'       => 'dal {dal} al {al}',
            'richiesta_approvata'  => 'La richiesta di {cosa} {periodo} e\' stata approvata.',
            'richiesta_rifiutata'  => 'La richiesta di {cosa} {periodo} e\' stata rifiutata: {motivo}',
            // ── Avvisi: pianificazione e documenti ──
            'avviso_pian_titolo'   => 'Programma del {data}',
            'avviso_pian_capo'     => 'Capo squadra: {nome}.',
            'avviso_pian_sei_capo' => 'Il capo squadra sei tu.',
            'avviso_pian_trasf'    => 'Trasferta.',
            'avviso_pian_rientro'  => 'Trasferta, rientro previsto il {data}.',
            'avviso_pian_tolto_t'  => 'Cambio di programma',
            'avviso_pian_tolto'    => 'Il {data} non sei piu\' in nessuna squadra. Se non torna, chiedi in ufficio.',
            'avviso_doc_nuovo_t'   => 'Nuovo documento',
            'avviso_doc_nuovo'     => 'C\'e\' un nuovo documento per te: {tipo}.',
            'avviso_doc_agg_t'     => 'Documento aggiornato',
            'avviso_doc_agg'       => 'Il tuo documento {tipo} e\' stato aggiornato.',
        ],
        'en' => [
            'giorni_settimana'     => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
            'oggi'                 => 'today',
            'e_cong'               => 'and',
            'promemoria_titolo'    => 'Attendance missing',
            'promemoria_uno'       => 'You still have to log {giorni}. It only takes a moment.',
            'promemoria_piu'       => 'You still have to log {giorni}. It only takes a moment.',
            'promemoria_uno_2'     => 'Last reminder: {giorni} is still not logged.',
            'promemoria_piu_2'     => 'Last reminder: {giorni} are still not logged.',
            'esito_presenza_ok'    => 'Attendance approved',
            'esito_presenza_ko'    => 'Attendance rejected',
            'presenza_approvata'   => 'Your attendance for {data} has been approved.',
            'presenza_rifiutata'   => 'Your attendance for {data} was rejected: {motivo}',
            'esito_richiesta_ok'   => 'Request approved',
            'esito_richiesta_ko'   => 'Request rejected',
            'cosa_ferie'           => 'leave',
            'cosa_permesso'        => 'time off',
            'cosa_malattia'        => 'sick leave',

            // ── Le pagine di /io ──────────────────────────
            'lingua_lbl'               => 'Language',
            'lingua_aiuto'             => 'Your pages and notifications come in this language.',
            'password_da_cambiare'     => 'Before you start, choose a password of your own.',
            'menu_oggi'                => 'Today and tomorrow',
            'menu_presenze'            => 'My attendance',
            'menu_assenze'             => 'Leave and absence',
            'documenti'                => 'Documents',
            'menu_cantieri'            => 'My sites',
            'apri'                     => 'Open',
            'nessun_cantiere'          => 'No site assigned.',
            'nome'                     => 'Name',
            'codice'                   => 'Code',
            'luogo'                    => 'Place',
            'ciao'                     => 'Hello {nome}',
            'oggi_lbl'                 => 'Today',
            'domani_lbl'               => 'Tomorrow',
            'cantiere_da_definire'     => 'Site to be confirmed',
            'auto'                     => 'Vehicle',
            'trasferta'                => 'Away job',
            'dorme_fuori'              => 'Overnight stay',
            'squadra'                  => 'Crew',
            'sei_capo'                 => 'You are the foreman',
            'con_te'                   => 'With you',
            'tu'                       => 'You',
            'capo'                     => 'foreman',
            'nessuna_squadra'          => 'You are not on any crew for today or tomorrow. If that looks wrong, ask the office.',
            'cosa_puoi_fare'           => 'What you can do',
            'ti_manca_una'             => '{n} day still to log:',
            'ti_mancano'               => '{n} days still to log:',
            'segnale'                  => 'Log them',
            'ultimi_due_mesi'          => 'Last two months',
            'da_segnare'               => 'To log',
            'giornata_intera'          => 'Full day',
            'mezza_giornata'           => 'Half day',
            'cantiere_da_scegliere'    => 'Site to choose',
            'scegli'                   => 'Choose',
            'nota_mezza'               => 'Half day, or did you eat out? Use Log another day below.',
            'segna_giornata'           => 'Log a day',
            'segna_altro'              => 'Log another day',
            'che_giorno'               => 'Which day',
            'dove_lavorato'            => 'Where you worked',
            'eri_qui'                  => 'That day you were here',
            'non_era_questo'           => 'It was not this site',
            'cerca_cantiere'           => 'Type the name or the code',
            'due_lettere'              => 'Type at least two letters and wait a moment',
            'quanto_lavorato'          => 'How long you worked',
            'extra'                    => 'Meals, hotel, vehicle',
            'pranzo_chi'               => 'Lunch - who paid?',
            'cena_chi'                 => 'Dinner - who paid?',
            'non_fatto'                => 'I did not',
            'io'                       => 'I did',
            'azienda'                  => 'The company',
            'dormito_fuori'            => 'I stayed overnight',
            'albergo'                  => 'Hotel',
            'albergo_ph'               => 'Name, if you stayed overnight',
            'targa'                    => 'Plate',
            'note'                     => 'Notes',
            'note_ph'                  => 'Anything the office should know',
            'manda'                    => 'Send to the office',
            'controlla_ufficio'        => 'The office checks it before recording it.',
            'tue_giornate'             => 'Your days',
            'giornate'                 => 'Days',
            'in_attesa_n'              => 'Pending',
            'trasferte'                => 'Away jobs',
            'rifiutate'                => 'Rejected',
            'cerca_giornata'           => 'Search site or day',
            'registrata'               => 'recorded',
            'in_attesa'                => 'pending',
            'rifiutata'                => 'rejected',
            'approvata'                => 'approved',
            'non_accettata'            => 'not accepted',
            'rifiutata_due'            => 'Rejected:',
            'ritira'                   => 'Withdraw',
            'ritirare_conferma'        => 'Withdraw this day?',
            'nessuna_giornata'         => 'No days in this month.',
            'nessuna_trovata'          => 'No days found.',
            'torna'                    => 'Back',
            'mese'                     => 'Month',
            'anno'                     => 'Year',
            'vai'                      => 'Go',
            'tue_assenze'              => 'Your absences',
            'chiesto_e_dato'           => 'What you asked for and what you were given',
            'chiedi_ferie'             => 'Request leave or report',
            'di_cosa'                  => 'What is it about',
            'ferie'                    => 'Leave',
            'permesso'                 => 'Time off',
            'malattia'                 => 'Sick leave',
            'dal'                      => 'From',
            'al'                       => 'To',
            'vuoto_un_giorno'          => 'Leave empty for a single day',
            'quante_ore'               => 'How many hours',
            'vuoto_intera'             => 'Empty = full day',
            'n_certificato'            => 'Certificate number',
            'cert_dopo'                => 'If you do not have it now, the office will add it',
            'note_qualcosa'            => 'Anything to add',
            'giorni_ferie'             => 'Leave days',
            'permessi'                 => 'Time off',
            'giorni_malattia'          => 'Sick days',
            'cerca_assenza'            => 'Search type, date or status',
            'nessuna_assenza'          => 'No leave, time off or sick leave in this year.',
            'nessuna_assenza_trovata'  => 'No absences found.',
            'ore'                      => 'hours',
            'cert'                     => 'cert.',
            'mezza_g'                  => 'half day',
            'cantiere_non_indicato'    => 'site not given',

            // ── Cosa gli si dice dopo che ha fatto qualcosa ──
            'msg_scegli_tutto'         => 'Choose the site and the day.',
            'msg_giorno_futuro'        => 'You cannot log a day that has not happened yet.',
            'msg_cantiere_chiuso'      => 'That site is not open. If that is wrong, tell the office.',
            'msg_gia_mandata'          => 'You already sent this day: it is pending.',
            'msg_mandata'              => 'Day {data} sent to the office. You will find it below as pending.',
            'msg_ritirata'             => 'Day withdrawn. You can send it again whenever you want.',
            'msg_non_ritirabile'       => 'It cannot be withdrawn any more: the office has already seen it.',
            'msg_scegli_tipo'          => 'Choose the type and the start day.',
            'msg_richiesta_mandata'    => '{cosa} {quando}: request sent to the office.',
            'msg_non_collegato'        => 'Your account is not linked to any worker. Tell the office.',
            'msg_errore'               => 'Something went wrong: {errore}',
            'per_il'                   => 'for {data}',
            'da_a'                     => 'from {dal} to {al}',
            'esito_malattia_ok'    => 'Sick leave recorded',
            'esito_malattia_ko'    => 'Sick leave not accepted',
            'malattia_registrata'  => 'Your sick leave {periodo} has been recorded.',
            'malattia_rifiutata'   => 'Your sick leave {periodo} was not accepted: {motivo}',
            'periodo_giorno'       => 'for {dal}',
            'periodo_dal_al'       => 'from {dal} to {al}',
            'richiesta_approvata'  => 'Your {cosa} request {periodo} has been approved.',
            'richiesta_rifiutata'  => 'Your {cosa} request {periodo} was rejected: {motivo}',
            'avviso_pian_titolo'   => 'Schedule for {data}',
            'avviso_pian_capo'     => 'Foreman: {nome}.',
            'avviso_pian_sei_capo' => 'You are the foreman.',
            'avviso_pian_trasf'    => 'Away job.',
            'avviso_pian_rientro'  => 'Away job, expected return on {data}.',
            'avviso_pian_tolto_t'  => 'Change of plan',
            'avviso_pian_tolto'    => 'On {data} you are no longer in any crew. If that is wrong, ask the office.',
            'avviso_doc_nuovo_t'   => 'New document',
            'avviso_doc_nuovo'     => 'There is a new document for you: {tipo}.',
            'avviso_doc_agg_t'     => 'Document updated',
            'avviso_doc_agg'       => 'Your document {tipo} has been updated.',
        ],
        'sq' => [
            'giorni_settimana'     => ['e hene', 'e marte', 'e merkure', 'e enjte', 'e premte', 'e shtune', 'e diel'],
            'oggi'                 => 'sot',
            'e_cong'               => 'dhe',
            'promemoria_titolo'    => 'Prezenca mungon',
            'promemoria_uno'       => 'Te mungon prezenca: {giorni}. Merr vetem pak sekonda.',
            'promemoria_piu'       => 'Te mungojne prezencat: {giorni}. Merr vetem pak sekonda.',
            'promemoria_uno_2'     => 'Kujtesa e fundit: te mungon ende prezenca: {giorni}.',
            'promemoria_piu_2'     => 'Kujtesa e fundit: te mungojne ende prezencat: {giorni}.',
            'esito_presenza_ok'    => 'Prezenca u aprovua',
            'esito_presenza_ko'    => 'Prezenca u refuzua',
            'presenza_approvata'   => 'Prezenca e dates {data} u aprovua.',
            'presenza_rifiutata'   => 'Prezenca e dates {data} u refuzua: {motivo}',
            'esito_richiesta_ok'   => 'Kerkesa u aprovua',
            'esito_richiesta_ko'   => 'Kerkesa u refuzua',
            'cosa_ferie'           => 'pushime',
            'cosa_permesso'        => 'leje',
            'cosa_malattia'        => 'semundje',

            // ── Le pagine di /io ──────────────────────────
            'lingua_lbl'               => 'Gjuha',
            'lingua_aiuto'             => 'Faqet e tua dhe njoftimet vijne ne kete gjuhe.',
            'password_da_cambiare'     => 'Para se te fillosh, zgjidh nje fjalekalim tendin.',
            'menu_oggi'                => 'Sot dhe neser',
            'menu_presenze'            => 'Prezencat e mia',
            'menu_assenze'             => 'Pushime dhe mungesa',
            'documenti'                => 'Dokumentet',
            'menu_cantieri'            => 'Kantieret e mi',
            'apri'                     => 'Hap',
            'nessun_cantiere'          => 'Asnje kantier i caktuar.',
            'nome'                     => 'Emri',
            'codice'                   => 'Kodi',
            'luogo'                    => 'Vendi',
            'ciao'                     => 'Pershendetje {nome}',
            'oggi_lbl'                 => 'Sot',
            'domani_lbl'               => 'Neser',
            'cantiere_da_definire'     => 'Kantieri do te caktohet',
            'auto'                     => 'Makina',
            'trasferta'                => 'Transferte',
            'dorme_fuori'              => 'Me fjetje',
            'squadra'                  => 'Skuadra',
            'sei_capo'                 => 'Ti je kryepuntori',
            'con_te'                   => 'Me ty jane',
            'tu'                       => 'Ti',
            'capo'                     => 'kryepuntor',
            'nessuna_squadra'          => 'Per sot dhe neser nuk je ne asnje skuadre. Nese nuk te duket e sakte, pyet ne zyre.',
            'cosa_puoi_fare'           => 'Cfare mund te besh',
            'ti_manca_una'             => 'Te mungon {n} dite per te shenuar:',
            'ti_mancano'               => 'Te mungojne {n} dite per te shenuar:',
            'segnale'                  => 'Shenoji',
            'ultimi_due_mesi'          => 'Dy muajt e fundit',
            'da_segnare'               => 'Per te shenuar',
            'giornata_intera'          => 'Dite e plote',
            'mezza_giornata'           => 'Gjysem dite',
            'cantiere_da_scegliere'    => 'Kantieri per te zgjedhur',
            'scegli'                   => 'Zgjidh',
            'nota_mezza'               => 'Gjysem dite, ose ke ngrene jashte? Perdor Sheno nje dite tjeter me poshte.',
            'segna_giornata'           => 'Sheno nje dite',
            'segna_altro'              => 'Sheno nje dite tjeter',
            'che_giorno'               => 'Cila dite',
            'dove_lavorato'            => 'Ku ke punuar',
            'eri_qui'                  => 'Ate dite ishe ketu',
            'non_era_questo'           => 'Nuk ishte ky kantier',
            'cerca_cantiere'           => 'Shkruaj emrin ose kodin',
            'due_lettere'              => 'Shkruaj te pakten dy shkronja dhe prit pak',
            'quanto_lavorato'          => 'Sa ke punuar',
            'extra'                    => 'Vakte, hotel, makine',
            'pranzo_chi'               => 'Dreka - kush pagoi?',
            'cena_chi'                 => 'Darka - kush pagoi?',
            'non_fatto'                => 'Nuk hengra',
            'io'                       => 'Une',
            'azienda'                  => 'Kompania',
            'dormito_fuori'            => 'Fjeta ne transferte',
            'albergo'                  => 'Hoteli',
            'albergo_ph'               => 'Emri, nese fjete ne transferte',
            'targa'                    => 'Targa',
            'note'                     => 'Shenime',
            'note_ph'                  => 'Nese ka dicka per te thene zyres',
            'manda'                    => 'Dergo ne zyre',
            'controlla_ufficio'        => 'Zyra e kontrollon para se ta regjistroje.',
            'tue_giornate'             => 'Ditet e tua',
            'giornate'                 => 'Dite',
            'in_attesa_n'              => 'Ne pritje',
            'trasferte'                => 'Transferta',
            'rifiutate'                => 'Te refuzuara',
            'cerca_giornata'           => 'Kerko kantier ose dite',
            'registrata'               => 'e regjistruar',
            'in_attesa'                => 'ne pritje',
            'rifiutata'                => 'e refuzuar',
            'approvata'                => 'e aprovuar',
            'non_accettata'            => 'nuk u pranua',
            'rifiutata_due'            => 'E refuzuar:',
            'ritira'                   => 'Terhiq',
            'ritirare_conferma'        => 'Ta terheqesh kete dite?',
            'nessuna_giornata'         => 'Asnje dite ne kete muaj.',
            'nessuna_trovata'          => 'Nuk u gjet asnje dite.',
            'torna'                    => 'Kthehu',
            'mese'                     => 'Muaji',
            'anno'                     => 'Viti',
            'vai'                      => 'Shko',
            'tue_assenze'              => 'Mungesat e tua',
            'chiesto_e_dato'           => 'Cfare ke kerkuar dhe cfare te kane dhene',
            'chiedi_ferie'             => 'Kerko pushime ose njofto',
            'di_cosa'                  => 'Per cfare behet fjale',
            'ferie'                    => 'Pushime',
            'permesso'                 => 'Leje',
            'malattia'                 => 'Semundje',
            'dal'                      => 'Nga',
            'al'                       => 'Deri',
            'vuoto_un_giorno'          => 'Lere bosh nese eshte vetem nje dite',
            'quante_ore'               => 'Sa ore',
            'vuoto_intera'             => 'Bosh = dite e plote',
            'n_certificato'            => 'Numri i certifikates',
            'cert_dopo'                => 'Nese nuk e ke tani, e shton zyra',
            'note_qualcosa'            => 'Nese ka dicka per te thene',
            'giorni_ferie'             => 'Dite pushimi',
            'permessi'                 => 'Leje',
            'giorni_malattia'          => 'Dite semundje',
            'cerca_assenza'            => 'Kerko llojin, daten ose gjendjen',
            'nessuna_assenza'          => 'Asnje pushim, leje ose semundje kete vit.',
            'nessuna_assenza_trovata'  => 'Nuk u gjet asnje mungese.',
            'ore'                      => 'ore',
            'cert'                     => 'cert.',
            'mezza_g'                  => 'gjysem dite',
            'cantiere_non_indicato'    => 'kantieri nuk eshte shenuar',

            // ── Cosa gli si dice dopo che ha fatto qualcosa ──
            'msg_scegli_tutto'         => 'Zgjidh kantierin dhe diten.',
            'msg_giorno_futuro'        => 'Nuk mund te shenosh nje dite qe nuk ka ardhur ende.',
            'msg_cantiere_chiuso'      => 'Ai kantier nuk eshte i hapur. Nese e kam gabim, thuaje ne zyre.',
            'msg_gia_mandata'          => 'Kete dite e ke derguar tashme: eshte ne pritje.',
            'msg_mandata'              => 'Dita {data} u dergua ne zyre. E gjen me poshte si ne pritje.',
            'msg_ritirata'             => 'Dita u terhoq. Mund ta dergosh perseri kur te duash.',
            'msg_non_ritirabile'       => 'Nuk mund te terhiqet me: zyra e ka pare tashme.',
            'msg_scegli_tipo'          => 'Zgjidh llojin dhe diten e fillimit.',
            'msg_richiesta_mandata'    => '{cosa} {quando}: kerkesa u dergua ne zyre.',
            'msg_non_collegato'        => 'Llogaria jote nuk eshte e lidhur me asnje punonjes. Thuaje ne zyre.',
            'msg_errore'               => 'Dicka nuk funksionoi: {errore}',
            'per_il'                   => 'e dates {data}',
            'da_a'                     => 'nga {dal} deri me {al}',
            'esito_malattia_ok'    => 'Semundja u regjistrua',
            'esito_malattia_ko'    => 'Semundja nuk u pranua',
            'malattia_registrata'  => 'Semundja {periodo} u regjistrua.',
            'malattia_rifiutata'   => 'Semundja {periodo} nuk u pranua: {motivo}',
            'periodo_giorno'       => 'per daten {dal}',
            'periodo_dal_al'       => 'nga {dal} deri me {al}',
            'richiesta_approvata'  => 'Kerkesa jote per {cosa} {periodo} u aprovua.',
            'richiesta_rifiutata'  => 'Kerkesa jote per {cosa} {periodo} u refuzua: {motivo}',
            'avviso_pian_titolo'   => 'Programi per {data}',
            'avviso_pian_capo'     => 'Kryepuntori: {nome}.',
            'avviso_pian_sei_capo' => 'Kryepuntori je ti.',
            'avviso_pian_trasf'    => 'Transferte.',
            'avviso_pian_rientro'  => 'Transferte, kthimi i parashikuar me {data}.',
            'avviso_pian_tolto_t'  => 'Ndryshim programi',
            'avviso_pian_tolto'    => 'Me {data} nuk je me ne asnje skuader. Nese nuk eshte e sakte, pyet zyren.',
            'avviso_doc_nuovo_t'   => 'Dokument i ri',
            'avviso_doc_nuovo'     => 'Ke nje dokument te ri: {tipo}.',
            'avviso_doc_agg_t'     => 'Dokument i perditesuar',
            'avviso_doc_agg'       => 'Dokumenti yt {tipo} u perditesua.',
        ],
        'ro' => [
            'giorni_settimana'     => ['luni', 'marti', 'miercuri', 'joi', 'vineri', 'sambata', 'duminica'],
            'oggi'                 => 'azi',
            'e_cong'               => 'si',
            'promemoria_titolo'    => 'Prezenta lipseste',
            'promemoria_uno'       => 'Iti lipseste prezenta de {giorni}. Dureaza doar cateva secunde.',
            'promemoria_piu'       => 'Iti lipsesc prezentele de {giorni}. Dureaza doar cateva secunde.',
            'promemoria_uno_2'     => 'Ultima reamintire: iti lipseste inca prezenta de {giorni}.',
            'promemoria_piu_2'     => 'Ultima reamintire: iti lipsesc inca prezentele de {giorni}.',
            'esito_presenza_ok'    => 'Prezenta aprobata',
            'esito_presenza_ko'    => 'Prezenta respinsa',
            'presenza_approvata'   => 'Prezenta din {data} a fost aprobata.',
            'presenza_rifiutata'   => 'Prezenta din {data} a fost respinsa: {motivo}',
            'esito_richiesta_ok'   => 'Cerere aprobata',
            'esito_richiesta_ko'   => 'Cerere respinsa',
            'cosa_ferie'           => 'concediu',
            'cosa_permesso'        => 'invoire',
            'cosa_malattia'        => 'boala',

            // ── Le pagine di /io ──────────────────────────
            'lingua_lbl'               => 'Limba',
            'lingua_aiuto'             => 'Paginile tale si notificarile vin in aceasta limba.',
            'password_da_cambiare'     => 'Inainte de a incepe, alege-ti o parola a ta.',
            'menu_oggi'                => 'Azi si maine',
            'menu_presenze'            => 'Prezentele mele',
            'menu_assenze'             => 'Concediu si absente',
            'documenti'                => 'Documente',
            'menu_cantieri'            => 'Santierele mele',
            'apri'                     => 'Deschide',
            'nessun_cantiere'          => 'Niciun santier atribuit.',
            'nome'                     => 'Nume',
            'codice'                   => 'Cod',
            'luogo'                    => 'Locul',
            'ciao'                     => 'Salut {nome}',
            'oggi_lbl'                 => 'Azi',
            'domani_lbl'               => 'Maine',
            'cantiere_da_definire'     => 'Santier de stabilit',
            'auto'                     => 'Masina',
            'trasferta'                => 'Deplasare',
            'dorme_fuori'              => 'Cu cazare',
            'squadra'                  => 'Echipa',
            'sei_capo'                 => 'Tu esti seful de echipa',
            'con_te'                   => 'Cu tine sunt',
            'tu'                       => 'Tu',
            'capo'                     => 'sef',
            'nessuna_squadra'          => 'Pentru azi si maine nu esti in nicio echipa. Daca nu e corect, intreaba la birou.',
            'cosa_puoi_fare'           => 'Ce poti face',
            'ti_manca_una'             => 'Iti lipseste {n} zi de inregistrat:',
            'ti_mancano'               => 'Iti lipsesc {n} zile de inregistrat:',
            'segnale'                  => 'Inregistreaza-le',
            'ultimi_due_mesi'          => 'Ultimele doua luni',
            'da_segnare'               => 'De inregistrat',
            'giornata_intera'          => 'Zi intreaga',
            'mezza_giornata'           => 'Jumatate de zi',
            'cantiere_da_scegliere'    => 'Santier de ales',
            'scegli'                   => 'Alege',
            'nota_mezza'               => 'Jumatate de zi, sau ai mancat afara? Foloseste Inregistreaza alta zi mai jos.',
            'segna_giornata'           => 'Inregistreaza o zi',
            'segna_altro'              => 'Inregistreaza alta zi',
            'che_giorno'               => 'Ce zi',
            'dove_lavorato'            => 'Unde ai lucrat',
            'eri_qui'                  => 'In ziua aceea erai aici',
            'non_era_questo'           => 'Nu era acest santier',
            'cerca_cantiere'           => 'Scrie numele sau codul',
            'due_lettere'              => 'Scrie cel putin doua litere si asteapta putin',
            'quanto_lavorato'          => 'Cat ai lucrat',
            'extra'                    => 'Mese, hotel, masina',
            'pranzo_chi'               => 'Pranzul - cine a platit?',
            'cena_chi'                 => 'Cina - cine a platit?',
            'non_fatto'                => 'Nu am mancat',
            'io'                       => 'Eu',
            'azienda'                  => 'Firma',
            'dormito_fuori'            => 'Am dormit in deplasare',
            'albergo'                  => 'Hotel',
            'albergo_ph'               => 'Numele, daca ai dormit in deplasare',
            'targa'                    => 'Numar auto',
            'note'                     => 'Observatii',
            'note_ph'                  => 'Daca e ceva de spus biroului',
            'manda'                    => 'Trimite la birou',
            'controlla_ufficio'        => 'Biroul o verifica inainte de a o inregistra.',
            'tue_giornate'             => 'Zilele tale',
            'giornate'                 => 'Zile',
            'in_attesa_n'              => 'In asteptare',
            'trasferte'                => 'Deplasari',
            'rifiutate'                => 'Respinse',
            'cerca_giornata'           => 'Cauta santier sau zi',
            'registrata'               => 'inregistrata',
            'in_attesa'                => 'in asteptare',
            'rifiutata'                => 'respinsa',
            'approvata'                => 'aprobata',
            'non_accettata'            => 'neacceptata',
            'rifiutata_due'            => 'Respinsa:',
            'ritira'                   => 'Retrage',
            'ritirare_conferma'        => 'Retragi aceasta zi?',
            'nessuna_giornata'         => 'Nicio zi in aceasta luna.',
            'nessuna_trovata'          => 'Nu s-a gasit nicio zi.',
            'torna'                    => 'Inapoi',
            'mese'                     => 'Luna',
            'anno'                     => 'Anul',
            'vai'                      => 'Afiseaza',
            'tue_assenze'              => 'Absentele tale',
            'chiesto_e_dato'           => 'Ce ai cerut si ce ti s-a dat',
            'chiedi_ferie'             => 'Cere concediu sau anunta',
            'di_cosa'                  => 'Despre ce este vorba',
            'ferie'                    => 'Concediu',
            'permesso'                 => 'Invoire',
            'malattia'                 => 'Boala',
            'dal'                      => 'De la',
            'al'                       => 'Pana la',
            'vuoto_un_giorno'          => 'Lasa gol daca e o singura zi',
            'quante_ore'               => 'Cate ore',
            'vuoto_intera'             => 'Gol = zi intreaga',
            'n_certificato'            => 'Numarul certificatului',
            'cert_dopo'                => 'Daca nu il ai acum, il adauga biroul',
            'note_qualcosa'            => 'Daca e ceva de spus',
            'giorni_ferie'             => 'Zile concediu',
            'permessi'                 => 'Invoiri',
            'giorni_malattia'          => 'Zile boala',
            'cerca_assenza'            => 'Cauta tipul, data sau starea',
            'nessuna_assenza'          => 'Niciun concediu, invoire sau boala in acest an.',
            'nessuna_assenza_trovata'  => 'Nu s-a gasit nicio absenta.',
            'ore'                      => 'ore',
            'cert'                     => 'cert.',
            'mezza_g'                  => 'jumatate de zi',
            'cantiere_non_indicato'    => 'santierul nu e indicat',

            // ── Cosa gli si dice dopo che ha fatto qualcosa ──
            'msg_scegli_tutto'         => 'Alege santierul si ziua.',
            'msg_giorno_futuro'        => 'Nu poti inregistra o zi care nu a venit inca.',
            'msg_cantiere_chiuso'      => 'Acel santier nu este deschis. Daca gresesc, spune la birou.',
            'msg_gia_mandata'          => 'Ai trimis deja aceasta zi: este in asteptare.',
            'msg_mandata'              => 'Ziua {data} a fost trimisa la birou. O gasesti mai jos ca in asteptare.',
            'msg_ritirata'             => 'Ziua a fost retrasa. O poti trimite din nou oricand.',
            'msg_non_ritirabile'       => 'Nu mai poate fi retrasa: biroul a vazut-o deja.',
            'msg_scegli_tipo'          => 'Alege tipul si ziua de inceput.',
            'msg_richiesta_mandata'    => '{cosa} {quando}: cererea a fost trimisa la birou.',
            'msg_non_collegato'        => 'Contul tau nu este legat de niciun muncitor. Spune la birou.',
            'msg_errore'               => 'Ceva nu a mers: {errore}',
            'per_il'                   => 'din {data}',
            'da_a'                     => 'din {dal} pana in {al}',
            'esito_malattia_ok'    => 'Boala inregistrata',
            'esito_malattia_ko'    => 'Boala neacceptata',
            'malattia_registrata'  => 'Boala {periodo} a fost inregistrata.',
            'malattia_rifiutata'   => 'Boala {periodo} nu a fost acceptata: {motivo}',
            'periodo_giorno'       => 'din {dal}',
            'periodo_dal_al'       => 'din {dal} pana in {al}',
            'richiesta_approvata'  => 'Cererea ta de {cosa} {periodo} a fost aprobata.',
            'richiesta_rifiutata'  => 'Cererea ta de {cosa} {periodo} a fost respinsa: {motivo}',
            'avviso_pian_titolo'   => 'Programul pentru {data}',
            'avviso_pian_capo'     => 'Sef de echipa: {nome}.',
            'avviso_pian_sei_capo' => 'Tu esti seful de echipa.',
            'avviso_pian_trasf'    => 'Deplasare.',
            'avviso_pian_rientro'  => 'Deplasare, intoarcere prevazuta pe {data}.',
            'avviso_pian_tolto_t'  => 'Schimbare de program',
            'avviso_pian_tolto'    => 'Pe {data} nu mai esti in nicio echipa. Daca nu e corect, intreaba la birou.',
            'avviso_doc_nuovo_t'   => 'Document nou',
            'avviso_doc_nuovo'     => 'Ai un document nou: {tipo}.',
            'avviso_doc_agg_t'     => 'Document actualizat',
            'avviso_doc_agg'       => 'Documentul tau {tipo} a fost actualizat.',
        ],
    ];

    /**
     * Il nome di un giorno della settimana.
     *
     * @param int $iso 1 = lunedi ... 7 = domenica, come date('N')
     */
    public static function giorno(int $iso, ?string $lingua): string
    {
        $l = self::normalizza($lingua);
        $nomi = self::TESTI[$l]['giorni_settimana'] ?? self::TESTI[self::RIPIEGO]['giorni_settimana'];

        return $nomi[$iso - 1] ?? '';
    }

    /**
     * Un elenco di giorni scritto come lo direbbe una persona.
     *
     * "lunedi, martedi e oggi" invece di "2026-09-28, 2026-09-29, 2026-09-30":
     * il promemoria si legge di sfuggita sulla schermata di blocco, e tre date
     * in cifre non dicono niente a nessuno.
     *
     * Il giorno corrente si chiama "oggi" e non col suo nome: e' quello che
     * uno ha in testa la sera, e sentirselo chiamare "mercoledi" costringe a
     * fermarsi un attimo a pensare che giorno e'.
     *
     * @param string[] $date elenco di aaaa-mm-gg, in ordine
     */
    public static function elencoGiorni(array $date, ?string $lingua, string $oggi): string
    {
        $nomi = [];
        foreach ($date as $d) {
            $nomi[] = $d === $oggi
                ? self::testo('oggi', $lingua)
                : self::giorno((int)date('N', strtotime($d)), $lingua);
        }

        if (count($nomi) <= 1) {
            return $nomi[0] ?? '';
        }

        $ultimo = array_pop($nomi);
        return implode(', ', $nomi) . ' ' . self::testo('e_cong', $lingua) . ' ' . $ultimo;
    }

    /** La lingua di un utente, ridotta a una che esiste davvero. */
    public static function normalizza(?string $lingua): string
    {
        $l = strtolower(trim((string)$lingua));

        // moldavo e rumeno sono la stessa lingua: stessi testi
        if ($l === 'mo') {
            return 'ro';
        }
        return isset(self::TESTI[$l]) ? $l : self::RIPIEGO;
    }

    /**
     * Un testo nella lingua chiesta.
     *
     * Se manca, si ripiega sull'italiano invece di restituire la chiave: una
     * notifica che dice "promemoria_primo" e' peggio di una in una lingua
     * sbagliata, perche' sembra un guasto.
     *
     * @param array<string, string|int> $valori sostituzioni per {segnaposto}
     */
    public static function testo(string $chiave, ?string $lingua, array $valori = []): string
    {
        $l = self::normalizza($lingua);

        $testo = self::TESTI[$l][$chiave]
              ?? self::TESTI[self::RIPIEGO][$chiave]
              ?? $chiave;

        // i giorni della settimana stanno nella stessa tabella ma sono un
        // elenco: chiederli come testo e' un errore di chi chiama, e
        // restituire "Array" sarebbe peggio del silenzio
        if (is_array($testo)) {
            return '';
        }

        foreach ($valori as $nome => $valore) {
            $testo = str_replace('{' . $nome . '}', (string)$valore, $testo);
        }
        return $testo;
    }
}
